<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RuntimeProductionProject>true</RuntimeProductionProject>
    <TargetFrameworks>net10.0;netstandard2.1</TargetFrameworks>
    <AssemblyName>Lumio.GameRuntime.Simulation</AssemblyName>
    <RootNamespace>Lumio.GameRuntime.Simulation</RootNamespace>
    <NoWarn>$(NoWarn);CA1711;CA1822;CA1825;CA1850;CA1859;CA1861;CA2263;CA1510;CA1512;CA1834</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../../../src/Lumio.GameRuntime.GeneratedContracts/Lumio.GameRuntime.GeneratedContracts.csproj" />
    <Compile Include="../../../../src/Lumio.GameRuntime.GeneratedContracts/Generated/Compatibility/IsExternalInit.cs" Link="Compatibility/IsExternalInit.cs" />
  </ItemGroup>
</Project>
