<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>Lumio.GameRuntime.HelloEntry</AssemblyName>
    <RootNamespace>Lumio.GameRuntime.HelloEntry</RootNamespace>
    <IsPackable>false</IsPackable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../src/Lumio.GameRuntime.Hello.csproj" />
  </ItemGroup>
</Project>
