<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RuntimeTestProject>true</RuntimeTestProject>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <OutputType>Exe</OutputType>
    <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Lumio.GameRuntime.Gas/Lumio.GameRuntime.Gas.csproj" />
    <ProjectReference Include="../../../ecs/src/Lumio.GameRuntime.Ecs/Lumio.GameRuntime.Ecs.csproj" />
    <ProjectReference Include="../../../command/src/Lumio.GameRuntime.Command/Lumio.GameRuntime.Command.csproj" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="Microsoft.Testing.Platform" />
    <PackageReference Include="coverlet.MTP" />
  </ItemGroup>
</Project>
