[CmdletBinding()]
param(
    [string] $OutputDirectory
)

# 生成一律锚定架构源的**已提交对象**,绝不读其工作区。理由与锚点优先级见 generate-contracts.sh 顶部注释。
$ErrorActionPreference = 'Stop'
# PowerShell 7.4 起 $PSNativeCommandUseErrorActionPreference 默认为 $true,原生命令非零退出会
# 抛终止性错误而不落到 $LASTEXITCODE——那样下面所有「跑 git 再查 $LASTEXITCODE」的守卫都走不到,
# 约定的哨兵字符串与 exit 31 会被一段未捕获异常 + exit 1 顶替。
$PSNativeCommandUseErrorActionPreference = $false
$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$architectureRoot = $env:LUMIO_ARCHITECTURE_ROOT
if ([string]::IsNullOrWhiteSpace($architectureRoot)) {
    [Console]::Error.WriteLine('ARCHITECTURE_ROOT_MISSING')
    exit 31
}
$architectureRoot = (Resolve-Path $architectureRoot).Path
& git -C $architectureRoot rev-parse --git-dir *> $null
if ($LASTEXITCODE -ne 0) {
    [Console]::Error.WriteLine("ARCHITECTURE_ROOT_NOT_A_REPOSITORY root=$architectureRoot")
    exit 31
}

$python = $env:LUMIO_PYTHON
if ([string]::IsNullOrWhiteSpace($python)) {
    foreach ($candidate in @('python3', 'python', 'py')) {
        $command = Get-Command $candidate -ErrorAction SilentlyContinue
        if ($null -ne $command) {
            $python = $command.Source
            break
        }
    }
}
if ([string]::IsNullOrWhiteSpace($python)) {
    [Console]::Error.WriteLine('PYTHON_MISSING')
    exit 31
}

$architectureRef = $env:LUMIO_ARCHITECTURE_COMMIT
if ([string]::IsNullOrWhiteSpace($architectureRef)) { $architectureRef = $env:LUMIO_ARCHITECTURE_REF }
if ([string]::IsNullOrWhiteSpace($architectureRef)) { $architectureRef = 'origin/main' }
$sourceCommit = (& git -C $architectureRoot rev-parse --verify --quiet "$architectureRef^{commit}" 2>$null | Out-String).Trim()
if ($sourceCommit -notmatch '^[0-9a-f]{40}$') {
    [Console]::Error.WriteLine("ARCHITECTURE_COMMIT_MISSING ref=$architectureRef")
    exit 31
}

if ([string]::IsNullOrWhiteSpace($OutputDirectory)) {
    $OutputDirectory = Join-Path $repoRoot 'src/Lumio.GameRuntime.GeneratedContracts/Generated'
}
$OutputDirectory = [IO.Path]::GetFullPath($OutputDirectory)
$temporaryRoot = Join-Path ([IO.Path]::GetTempPath()) ('lumio-contracts-' + [Guid]::NewGuid().ToString('N'))
New-Item -ItemType Directory -Path $temporaryRoot | Out-Null
try {
    # 只读物化该 commit 的树。用 git archive 而非 git worktree add:后者会往架构源仓的 .git
    # 写 worktree 注册记录,而那个仓正被并发编辑。archive 必须写文件再解包——PowerShell
    # 管道会按文本处理字节流,直接 pipe 会损坏 tar。
    # 三个 -c 与 pathspec 限定的理由见 generate-contracts.sh 同处注释:前者堵住三条会让导出字节
    # 随机器变化的通道(core.autocrlf / core.eol / 全局 attributesfile),后者把全树的 42 个符号
    # 链接降到 0——Windows 的 tar 在未开 Developer Mode 时创建符号链接会失败。
    # 残留未闭合:$GIT_DIR/info/attributes 无 config 开关。
    $architectureSnapshot = Join-Path $temporaryRoot 'architecture'
    New-Item -ItemType Directory -Path $architectureSnapshot | Out-Null
    $archivePath = Join-Path $temporaryRoot 'architecture.tar'
    # Windows 上没有 /dev/null 设备路径,用 NUL;两者都只是「一个空的 attributes 文件」。
    $nullAttributes = if ($IsWindows -or $env:OS -eq 'Windows_NT') { 'NUL' } else { '/dev/null' }
    & git -C $architectureRoot -c core.autocrlf=false -c core.eol=lf -c core.attributesfile=$nullAttributes `
        archive --format=tar --output=$archivePath $sourceCommit tools schemas ids fixtures
    if ($LASTEXITCODE -ne 0) {
        [Console]::Error.WriteLine("ARCHITECTURE_SNAPSHOT_FAILED commit=$sourceCommit")
        exit 31
    }
    & tar -x -f $archivePath -C $architectureSnapshot
    if ($LASTEXITCODE -ne 0) {
        [Console]::Error.WriteLine("ARCHITECTURE_SNAPSHOT_FAILED commit=$sourceCommit")
        exit 31
    }
    $tool = Join-Path $architectureSnapshot 'tools/lumio_contract.py'
    if (-not (Test-Path -LiteralPath $tool -PathType Leaf)) {
        # 报真实 root,不报临时快照路径——快照路径对排障没有意义。
        [Console]::Error.WriteLine("ARCHITECTURE_TOOL_MISSING root=$architectureRoot commit=$sourceCommit")
        exit 31
    }
    # 之后所有注册表读取都必须落在快照上,不得再碰工作区。
    $architectureRoot = $architectureSnapshot

    & $python $tool generate --out (Join-Path $temporaryRoot 'packages')
    if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }

    $indexPath = Join-Path $temporaryRoot 'packages/index.json'
    $packagesRoot = Join-Path $temporaryRoot 'packages'
    $index = Get-Content -LiteralPath $indexPath -Raw | ConvertFrom-Json
    $artifacts = @($index.artifacts | Where-Object { $_.language -eq 'csharp' } | Sort-Object artifactId)
    if ($artifacts.Count -ne 6) { throw 'expected six C# architecture artifacts' }

    if (Test-Path -LiteralPath $OutputDirectory) {
        Get-ChildItem -LiteralPath $OutputDirectory -Force | Remove-Item -Recurse -Force
    } else {
        New-Item -ItemType Directory -Path $OutputDirectory -Force | Out-Null
    }
    $compatibilityDirectory = Join-Path $OutputDirectory 'Compatibility'
    New-Item -ItemType Directory -Path $compatibilityDirectory -Force | Out-Null
    [IO.File]::WriteAllText(
        (Join-Path $compatibilityDirectory 'IsExternalInit.cs'),
        "// <auto-generated />`n// Compatibility declaration emitted by the generated-contract wrapper.`nnamespace System.Runtime.CompilerServices;`ninternal sealed class IsExternalInit;`n",
        [Text.UTF8Encoding]::new($false))

    function ConvertTo-JsonString([string] $Value) {
        return (ConvertTo-Json -InputObject $Value -Compress)
    }
    function Get-Sha256([string] $Path) {
        return (Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToLowerInvariant()
    }
    function Format-Array([object[]] $Values) {
        if ($Values.Count -eq 0) { return 'new[] { }' }
        $lines = @('new[] {')
        foreach ($value in $Values) { $lines += ('        ' + (ConvertTo-JsonString ([string] $value)) + ',') }
        $lines += '    }'
        return ($lines -join "`n")
    }

    $artifactIds = @($artifacts | ForEach-Object { [string] $_.artifactId })
    $artifactKinds = @($artifacts | ForEach-Object { [string] $_.artifactKind })
    $artifactHashPairs = @($artifacts | ForEach-Object { [PSCustomObject]@{ Id = [string] $_.artifactId; Hash = [string] $_.outputHash } })
    $schemaIndex = Get-Content -LiteralPath (Join-Path $architectureRoot 'schemas/index.json') -Raw | ConvertFrom-Json
    $schemaIds = @($schemaIndex.schemas | ForEach-Object { [string] $_.id })
    $required = @('txn-journal-record', 'command-log-record', 'wal-record-envelope', 'voxel-world-port', 'voxel-snapshot-payload', 'replication-envelope', 'config-table', 'logging-event', 'failure-bundle')
    $schemaHash = Get-Sha256 (Join-Path $architectureRoot 'schemas/index.json')
    $idHash = Get-Sha256 (Join-Path $architectureRoot 'ids/index.json')
    $fixtureHash = Get-Sha256 (Join-Path $architectureRoot 'fixtures/index.json')

    foreach ($artifact in $artifacts) {
        $package = Join-Path $packagesRoot ([string] $artifact.packagePath)
        $target = Join-Path $OutputDirectory ('Artifacts/' + [string] $artifact.artifactId)
        New-Item -ItemType Directory -Path $target -Force | Out-Null
        $sources = @(Get-ChildItem -LiteralPath $package -Filter '*.cs' -File | Sort-Object Name)
        if ($sources.Count -eq 0) { throw "artifact has no C# source: $($artifact.artifactId)" }
        foreach ($source in $sources) {
            $content = Get-Content -LiteralPath $source.FullName -Raw
            $text = "// <auto-generated />`n// Generated by LumioGameEngineArchitecture; do not edit.`n" + $content.Replace("`r`n", "`n")
            [IO.File]::WriteAllText((Join-Path $target $source.Name), $text, [Text.UTF8Encoding]::new($false))
        }
    }

    $artifactHashJson = ($artifactHashPairs | ForEach-Object { (ConvertTo-JsonString $_.Id) + ':' + (ConvertTo-JsonString $_.Hash) }) -join ','
    $manifestJson = '{' +
        '"architectureBaselineId":' + (ConvertTo-JsonString ([string] $index.baselineId)) + ',' +
        '"architectureSourceCommit":' + (ConvertTo-JsonString $sourceCommit) + ',' +
        '"artifactHashes":{' + $artifactHashJson + '},' +
        '"artifactIds":[' + (($artifactIds | ForEach-Object { ConvertTo-JsonString $_ }) -join ',') + '],' +
        '"artifactKinds":[' + (($artifactKinds | ForEach-Object { ConvertTo-JsonString $_ }) -join ',') + '],' +
        '"compilerHash":' + (ConvertTo-JsonString ([string] $index.compilerHash)) + ',' +
        '"fixtureRegistrySha256":' + (ConvertTo-JsonString $fixtureHash) + ',' +
        '"idRegistrySha256":' + (ConvertTo-JsonString $idHash) + ',' +
        '"inputHash":' + (ConvertTo-JsonString ([string] $index.inputHash)) + ',' +
        '"requiredContractNames":[' + (($required | ForEach-Object { ConvertTo-JsonString $_ }) -join ',') + '],' +
        '"schemaEpoch":' + ([int] $index.schemaEpoch) + ',' +
        '"schemaIds":[' + (($schemaIds | ForEach-Object { ConvertTo-JsonString $_ }) -join ',') + '],' +
        '"schemaRegistrySha256":' + (ConvertTo-JsonString $schemaHash) + '}'
    [IO.File]::WriteAllText((Join-Path $OutputDirectory 'generated-contract-manifest.json'), ($manifestJson + "`n"), [Text.UTF8Encoding]::new($false))

    $hashEntries = ($artifactHashPairs | ForEach-Object { '        [' + (ConvertTo-JsonString $_.Id) + '] = ' + (ConvertTo-JsonString $_.Hash) + ',' }) -join "`n"
    $source = @"
// <auto-generated />
// Generated by LumioGameEngineArchitecture; do not edit.
using System;
using System.Collections.Generic;

namespace Lumio.GameRuntime.GeneratedContracts;

public static class GeneratedContractManifest
{
    public const string ArchitectureBaselineId = $(ConvertTo-JsonString ([string] $index.baselineId));
    public const string ArchitectureSourceCommit = $(ConvertTo-JsonString $sourceCommit);
    public const int SchemaEpoch = $([int] $index.schemaEpoch);
    public const string CompilerHash = $(ConvertTo-JsonString ([string] $index.compilerHash));
    public const string InputHash = $(ConvertTo-JsonString ([string] $index.inputHash));
    public const string SchemaRegistrySha256 = $(ConvertTo-JsonString $schemaHash);
    public const string IdRegistrySha256 = $(ConvertTo-JsonString $idHash);
    public const string FixtureRegistrySha256 = $(ConvertTo-JsonString $fixtureHash);
    public static IReadOnlyList<string> ArtifactIds { get; } = $(Format-Array $artifactIds);
    public static IReadOnlyList<string> ArtifactKinds { get; } = $(Format-Array $artifactKinds);
    public static IReadOnlyList<string> SchemaIds { get; } = $(Format-Array $schemaIds);
    public static IReadOnlyList<string> RequiredContractNames { get; } = $(Format-Array $required);
    public static IReadOnlyDictionary<string, string> ArtifactHashes { get; } =
        new Dictionary<string, string>(StringComparer.Ordinal)
        {
$hashEntries
        };
}

public static class RequiredContractNames
{
    public static IReadOnlyList<string> All => GeneratedContractManifest.RequiredContractNames;
}

public static class GeneratedContractCatalog
{
    public static bool Contains(string name)
    {
        if (name is null) return false;
        foreach (string value in GeneratedContractManifest.SchemaIds)
        {
            if (string.Equals(value, name, StringComparison.Ordinal)) return true;
        }
        return false;
    }
}
"@
    [IO.File]::WriteAllText((Join-Path $OutputDirectory 'GeneratedContractManifest.cs'), ($source.TrimStart("`r", "`n").Replace("`r`n", "`n") + "`n"), [Text.UTF8Encoding]::new($false))
    $baseline = [string] $index.baselineId
    Write-Output "GENERATED_CONTRACTS_OK baseline=$baseline output=$OutputDirectory"
} finally {
    if (Test-Path -LiteralPath $temporaryRoot) { Remove-Item -LiteralPath $temporaryRoot -Recurse -Force }
}
