#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
architecture_root="${LUMIO_ARCHITECTURE_ROOT:-}"
if [[ -z "$architecture_root" ]]; then
  printf 'ARCHITECTURE_ROOT_MISSING\n' >&2
  exit 31
fi
if [[ ! -f "$architecture_root/tools/lumio_contract.py" ]]; then
  printf 'ARCHITECTURE_TOOL_MISSING root=%s\n' "$architecture_root" >&2
  exit 31
fi

python_command="${LUMIO_PYTHON:-}"
if [[ -z "$python_command" ]]; then
  if command -v python3 >/dev/null 2>&1; then
    python_command="$(command -v python3)"
  elif command -v python >/dev/null 2>&1; then
    python_command="$(command -v python)"
  else
    printf 'PYTHON_MISSING\n' >&2
    exit 31
  fi
fi

source_commit="$(git -C "$architecture_root" rev-parse HEAD 2>/dev/null || true)"
if [[ ! "$source_commit" =~ ^[0-9a-fA-F]{40}$ ]]; then
  printf 'ARCHITECTURE_COMMIT_MISSING\n' >&2
  exit 31
fi

output_directory="${LUMIO_GENERATED_OUTPUT:-$repo_root/src/Lumio.GameRuntime.GeneratedContracts/Generated}"
temporary_root="$(mktemp -d "${TMPDIR:-/tmp}/lumio-contracts.XXXXXX")"
trap 'rm -rf "$temporary_root"' EXIT

"$python_command" "$architecture_root/tools/lumio_contract.py" generate --out "$temporary_root/packages"

"$python_command" - "$temporary_root/packages/index.json" "$temporary_root/packages" "$architecture_root" "$output_directory" "$source_commit" <<'PY'
import hashlib
import json
import shutil
import sys
from pathlib import Path


index_path, packages_root, architecture_root, output_root, source_commit = map(Path, sys.argv[1:])
output_root.mkdir(parents=True, exist_ok=True)
for child in output_root.iterdir():
    if child.is_dir():
        shutil.rmtree(child)
    else:
        child.unlink()

index = json.loads(index_path.read_text(encoding="utf-8"))
architecture_root = Path(architecture_root)
output_root = Path(output_root)
(output_root / "Compatibility").mkdir(parents=True, exist_ok=True)
(output_root / "Compatibility" / "IsExternalInit.cs").write_text(
    "// <auto-generated />\n"
    "// Compatibility declaration emitted by the generated-contract wrapper.\n"
    "namespace System.Runtime.CompilerServices;\n"
    "internal sealed class IsExternalInit;\n",
    encoding="utf-8",
    newline="\n",
)

def file_hash(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()

def csharp(value: str) -> str:
    return json.dumps(str(value), ensure_ascii=True)

def array_block(values):
    if not values:
        return "new[] { }"
    return "new[] {\n" + "".join("        " + csharp(value) + ",\n" for value in values) + "    }"

artifacts = sorted(
    (item for item in index["artifacts"] if item.get("language") == "csharp"),
    key=lambda item: item["artifactId"],
)
if len(artifacts) != 6:
    raise SystemExit("expected six C# architecture artifacts")

artifact_ids = [item["artifactId"] for item in artifacts]
artifact_kinds = [item["artifactKind"] for item in artifacts]
artifact_hashes = {item["artifactId"]: item["outputHash"] for item in artifacts}
schema_index = json.loads((architecture_root / "schemas" / "index.json").read_text(encoding="utf-8"))
schema_ids = [item["id"] for item in schema_index.get("schemas", [])]
id_index = architecture_root / "ids" / "index.json"
fixture_index = architecture_root / "fixtures" / "index.json"
schema_registry = architecture_root / "schemas" / "index.json"

for artifact in artifacts:
    package = Path(packages_root) / Path(artifact["packagePath"])
    target = output_root / "Artifacts" / artifact["artifactId"]
    target.mkdir(parents=True, exist_ok=True)
    sources = sorted(package.glob("*.cs"), key=lambda path: path.name)
    if not sources:
        raise SystemExit(f"artifact has no C# source: {artifact['artifactId']}")
    for source in sources:
        destination = target / source.name
        content = source.read_text(encoding="utf-8")
        destination.write_text(
            "// <auto-generated />\n"
            "// Generated by LumioGameEngineArchitecture; do not edit.\n"
            + content.replace("\r\n", "\n"),
            encoding="utf-8",
            newline="\n",
        )

required = [
    "txn-journal-record",
    "command-log-record",
    "wal-record-envelope",
    "voxel-world-port",
    "voxel-snapshot-payload",
    "replication-envelope",
    "config-table",
    "logging-event",
    "failure-bundle",
]
manifest = {
    "architectureBaselineId": index["baselineId"],
    "architectureSourceCommit": str(source_commit),
    "schemaEpoch": index["schemaEpoch"],
    "compilerHash": index["compilerHash"],
    "inputHash": index["inputHash"],
    "artifactHashes": artifact_hashes,
    "artifactIds": artifact_ids,
    "artifactKinds": artifact_kinds,
    "schemaIds": schema_ids,
    "requiredContractNames": required,
    "schemaRegistrySha256": file_hash(schema_registry),
    "idRegistrySha256": file_hash(id_index),
    "fixtureRegistrySha256": file_hash(fixture_index),
}
(output_root / "generated-contract-manifest.json").write_text(
    json.dumps(manifest, ensure_ascii=True, sort_keys=True, separators=(",", ":")) + "\n",
    encoding="utf-8",
    newline="\n",
)

hash_entries = "\n".join(
    f"        [{csharp(key)}] = {csharp(value)}," for key, value in sorted(artifact_hashes.items())
)
source = f'''// <auto-generated />
// Generated by LumioGameEngineArchitecture; do not edit.
using System;
using System.Collections.Generic;

namespace Lumio.GameRuntime.GeneratedContracts;

public static class GeneratedContractManifest
{{
    public const string ArchitectureBaselineId = {csharp(index["baselineId"])};
    public const string ArchitectureSourceCommit = {csharp(source_commit)};
    public const int SchemaEpoch = {int(index["schemaEpoch"])};
    public const string CompilerHash = {csharp(index["compilerHash"])};
    public const string InputHash = {csharp(index["inputHash"])};
    public const string SchemaRegistrySha256 = {csharp(manifest["schemaRegistrySha256"])};
    public const string IdRegistrySha256 = {csharp(manifest["idRegistrySha256"])};
    public const string FixtureRegistrySha256 = {csharp(manifest["fixtureRegistrySha256"])};
    public static IReadOnlyList<string> ArtifactIds {{ get; }} = {array_block(artifact_ids)};
    public static IReadOnlyList<string> ArtifactKinds {{ get; }} = {array_block(artifact_kinds)};
    public static IReadOnlyList<string> SchemaIds {{ get; }} = {array_block(schema_ids)};
    public static IReadOnlyList<string> RequiredContractNames {{ get; }} = {array_block(required)};
    public static IReadOnlyDictionary<string, string> ArtifactHashes {{ get; }} =
        new Dictionary<string, string>(StringComparer.Ordinal)
        {{
{hash_entries}
        }};
}}

public static class RequiredContractNames
{{
    public static IReadOnlyList<string> All => GeneratedContractManifest.RequiredContractNames;
}}

public static class GeneratedContractCatalog
{{
    public static bool Contains(string name)
    {{
        if (name is null) return false;
        foreach (string value in GeneratedContractManifest.SchemaIds)
        {{
            if (string.Equals(value, name, StringComparison.Ordinal)) return true;
        }}
        return false;
    }}
}}
'''
(output_root / "GeneratedContractManifest.cs").write_text(source, encoding="utf-8", newline="\n")
PY

baseline="$(sed -n 's/.*"architectureBaselineId":"\([^"]*\)".*/\1/p' "$output_directory/generated-contract-manifest.json")"
printf 'GENERATED_CONTRACTS_OK baseline=%s output=%s\n' "$baseline" "$output_directory"
