[CmdletBinding()]
param(
    [string] $OutputDirectory
)

$ErrorActionPreference = 'Stop'
$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$architectureRoot = $env:LUMIO_ARCHITECTURE_ROOT
if ([string]::IsNullOrWhiteSpace($architectureRoot)) {
    [Console]::Error.WriteLine('ARCHITECTURE_ROOT_MISSING')
    exit 31
}
$architectureRoot = (Resolve-Path $architectureRoot).Path
$tool = Join-Path $architectureRoot 'tools/lumio_contract.py'
if (-not (Test-Path -LiteralPath $tool -PathType Leaf)) {
    [Console]::Error.WriteLine("ARCHITECTURE_TOOL_MISSING root=$architectureRoot")
    exit 31
}

$python = $env:LUMIO_PYTHON
if ([string]::IsNullOrWhiteSpace($python)) {
    foreach ($candidate in @('python3', 'python', 'py')) {
        $command = Get-Command $candidate -ErrorAction SilentlyContinue
        if ($null -ne $command) {
            $python = $command.Source
            break
        }
    }
}
if ([string]::IsNullOrWhiteSpace($python)) {
    [Console]::Error.WriteLine('PYTHON_MISSING')
    exit 31
}

$sourceCommit = (& git -C $architectureRoot rev-parse HEAD 2>$null | Out-String).Trim()
if ($sourceCommit -notmatch '^[0-9a-fA-F]{40}$') {
    [Console]::Error.WriteLine('ARCHITECTURE_COMMIT_MISSING')
    exit 31
}

if ([string]::IsNullOrWhiteSpace($OutputDirectory)) {
    $OutputDirectory = Join-Path $repoRoot 'src/Lumio.GameRuntime.GeneratedContracts/Generated'
}
$OutputDirectory = [IO.Path]::GetFullPath($OutputDirectory)
$temporaryRoot = Join-Path ([IO.Path]::GetTempPath()) ('lumio-contracts-' + [Guid]::NewGuid().ToString('N'))
New-Item -ItemType Directory -Path $temporaryRoot | Out-Null
try {
    & $python $tool generate --out (Join-Path $temporaryRoot 'packages')
    if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }

    $indexPath = Join-Path $temporaryRoot 'packages/index.json'
    $packagesRoot = Join-Path $temporaryRoot 'packages'
    $index = Get-Content -LiteralPath $indexPath -Raw | ConvertFrom-Json
    $artifacts = @($index.artifacts | Where-Object { $_.language -eq 'csharp' } | Sort-Object artifactId)
    if ($artifacts.Count -ne 6) { throw 'expected six C# architecture artifacts' }

    if (Test-Path -LiteralPath $OutputDirectory) {
        Get-ChildItem -LiteralPath $OutputDirectory -Force | Remove-Item -Recurse -Force
    } else {
        New-Item -ItemType Directory -Path $OutputDirectory -Force | Out-Null
    }
    $compatibilityDirectory = Join-Path $OutputDirectory 'Compatibility'
    New-Item -ItemType Directory -Path $compatibilityDirectory -Force | Out-Null
    [IO.File]::WriteAllText(
        (Join-Path $compatibilityDirectory 'IsExternalInit.cs'),
        "// <auto-generated />`n// Compatibility declaration emitted by the generated-contract wrapper.`nnamespace System.Runtime.CompilerServices;`ninternal sealed class IsExternalInit;`n",
        [Text.UTF8Encoding]::new($false))

    function ConvertTo-JsonString([string] $Value) {
        return (ConvertTo-Json -InputObject $Value -Compress)
    }
    function Get-Sha256([string] $Path) {
        return (Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToLowerInvariant()
    }
    function Format-Array([object[]] $Values) {
        if ($Values.Count -eq 0) { return 'new[] { }' }
        $lines = @('new[] {')
        foreach ($value in $Values) { $lines += ('        ' + (ConvertTo-JsonString ([string] $value)) + ',') }
        $lines += '    }'
        return ($lines -join "`n")
    }

    $artifactIds = @($artifacts | ForEach-Object { [string] $_.artifactId })
    $artifactKinds = @($artifacts | ForEach-Object { [string] $_.artifactKind })
    $artifactHashPairs = @($artifacts | ForEach-Object { [PSCustomObject]@{ Id = [string] $_.artifactId; Hash = [string] $_.outputHash } })
    $schemaIndex = Get-Content -LiteralPath (Join-Path $architectureRoot 'schemas/index.json') -Raw | ConvertFrom-Json
    $schemaIds = @($schemaIndex.schemas | ForEach-Object { [string] $_.id })
    $required = @('txn-journal-record', 'command-log-record', 'wal-record-envelope', 'voxel-world-port', 'voxel-snapshot-payload', 'replication-envelope', 'config-table', 'logging-event', 'failure-bundle')
    $schemaHash = Get-Sha256 (Join-Path $architectureRoot 'schemas/index.json')
    $idHash = Get-Sha256 (Join-Path $architectureRoot 'ids/index.json')
    $fixtureHash = Get-Sha256 (Join-Path $architectureRoot 'fixtures/index.json')

    foreach ($artifact in $artifacts) {
        $package = Join-Path $packagesRoot ([string] $artifact.packagePath)
        $target = Join-Path $OutputDirectory ('Artifacts/' + [string] $artifact.artifactId)
        New-Item -ItemType Directory -Path $target -Force | Out-Null
        $sources = @(Get-ChildItem -LiteralPath $package -Filter '*.cs' -File | Sort-Object Name)
        if ($sources.Count -eq 0) { throw "artifact has no C# source: $($artifact.artifactId)" }
        foreach ($source in $sources) {
            $content = Get-Content -LiteralPath $source.FullName -Raw
            $text = "// <auto-generated />`n// Generated by LumioGameEngineArchitecture; do not edit.`n" + $content.Replace("`r`n", "`n")
            [IO.File]::WriteAllText((Join-Path $target $source.Name), $text, [Text.UTF8Encoding]::new($false))
        }
    }

    $artifactHashJson = ($artifactHashPairs | ForEach-Object { (ConvertTo-JsonString $_.Id) + ':' + (ConvertTo-JsonString $_.Hash) }) -join ','
    $manifestJson = '{' +
        '"architectureBaselineId":' + (ConvertTo-JsonString ([string] $index.baselineId)) + ',' +
        '"architectureSourceCommit":' + (ConvertTo-JsonString $sourceCommit) + ',' +
        '"artifactHashes":{' + $artifactHashJson + '},' +
        '"artifactIds":[' + (($artifactIds | ForEach-Object { ConvertTo-JsonString $_ }) -join ',') + '],' +
        '"artifactKinds":[' + (($artifactKinds | ForEach-Object { ConvertTo-JsonString $_ }) -join ',') + '],' +
        '"compilerHash":' + (ConvertTo-JsonString ([string] $index.compilerHash)) + ',' +
        '"fixtureRegistrySha256":' + (ConvertTo-JsonString $fixtureHash) + ',' +
        '"idRegistrySha256":' + (ConvertTo-JsonString $idHash) + ',' +
        '"inputHash":' + (ConvertTo-JsonString ([string] $index.inputHash)) + ',' +
        '"requiredContractNames":[' + (($required | ForEach-Object { ConvertTo-JsonString $_ }) -join ',') + '],' +
        '"schemaEpoch":' + ([int] $index.schemaEpoch) + ',' +
        '"schemaIds":[' + (($schemaIds | ForEach-Object { ConvertTo-JsonString $_ }) -join ',') + '],' +
        '"schemaRegistrySha256":' + (ConvertTo-JsonString $schemaHash) + '}'
    [IO.File]::WriteAllText((Join-Path $OutputDirectory 'generated-contract-manifest.json'), ($manifestJson + "`n"), [Text.UTF8Encoding]::new($false))

    $hashEntries = ($artifactHashPairs | ForEach-Object { '        [' + (ConvertTo-JsonString $_.Id) + '] = ' + (ConvertTo-JsonString $_.Hash) + ',' }) -join "`n"
    $source = @"
// <auto-generated />
// Generated by LumioGameEngineArchitecture; do not edit.
using System;
using System.Collections.Generic;

namespace Lumio.GameRuntime.GeneratedContracts;

public static class GeneratedContractManifest
{
    public const string ArchitectureBaselineId = $(ConvertTo-JsonString ([string] $index.baselineId));
    public const string ArchitectureSourceCommit = $(ConvertTo-JsonString $sourceCommit);
    public const int SchemaEpoch = $([int] $index.schemaEpoch);
    public const string CompilerHash = $(ConvertTo-JsonString ([string] $index.compilerHash));
    public const string InputHash = $(ConvertTo-JsonString ([string] $index.inputHash));
    public const string SchemaRegistrySha256 = $(ConvertTo-JsonString $schemaHash);
    public const string IdRegistrySha256 = $(ConvertTo-JsonString $idHash);
    public const string FixtureRegistrySha256 = $(ConvertTo-JsonString $fixtureHash);
    public static IReadOnlyList<string> ArtifactIds { get; } = $(Format-Array $artifactIds);
    public static IReadOnlyList<string> ArtifactKinds { get; } = $(Format-Array $artifactKinds);
    public static IReadOnlyList<string> SchemaIds { get; } = $(Format-Array $schemaIds);
    public static IReadOnlyList<string> RequiredContractNames { get; } = $(Format-Array $required);
    public static IReadOnlyDictionary<string, string> ArtifactHashes { get; } =
        new Dictionary<string, string>(StringComparer.Ordinal)
        {
$hashEntries
        };
}

public static class RequiredContractNames
{
    public static IReadOnlyList<string> All => GeneratedContractManifest.RequiredContractNames;
}

public static class GeneratedContractCatalog
{
    public static bool Contains(string name)
    {
        if (name is null) return false;
        foreach (string value in GeneratedContractManifest.SchemaIds)
        {
            if (string.Equals(value, name, StringComparison.Ordinal)) return true;
        }
        return false;
    }
}
"@
    [IO.File]::WriteAllText((Join-Path $OutputDirectory 'GeneratedContractManifest.cs'), ($source.TrimStart("`r", "`n").Replace("`r`n", "`n") + "`n"), [Text.UTF8Encoding]::new($false))
    $baseline = [string] $index.baselineId
    Write-Output "GENERATED_CONTRACTS_OK baseline=$baseline output=$OutputDirectory"
} finally {
    if (Test-Path -LiteralPath $temporaryRoot) { Remove-Item -LiteralPath $temporaryRoot -Recurse -Force }
}
